### ISSUE TITLE
support to match names against https://ucjeps.berkeley.edu/eflora/

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/nomer#97]

**Comment by jhpoelen** [comment]
@jtmiller28 how badly do you want to index ucjeps ? Would this only focus on California flora?

**Comment by jtmiller28** [comment]
I would enjoy being able to compare resolution, but for my current project its out of scope since ucjep's resolution is specific to California Flora only. Once you cross state boundaries it becomes less useful for designations, in fact it would likely be detrimental to assume the taxonomy of outside areas follows their catalogue. If it is possible in the future, it would make an interesting case study just to subset flora out by California's boundary and compare resolution services however since they are said to have the most accurate name database for California.

**Comment by jhpoelen** [comment]
@jtmiller28 thanks for clarifying! Closing this issue for now. If someone has a desire to support it, we can re-open /re-consider.
